/* 任务流转中心 / Mission Transfer Center — 时刻轴版本的电商采集与监控任务数据 */
window.TRANSFER_CENTER_V2 = {
  company: "华东零售",
  title: "任务流转中心",
  titleEn: "Mission Transfer Center",
  /* 快照时间：所有相对时间都以此刻为基准，方便原型演示 */
  now: "2026-08-18T09:42:00+08:00",
  timezone: "Asia/Shanghai",
  viewer: { id: "zhouqi", name: "周琪", role: "值班" },
  people: {
    lin: { name: "林晓禾", role: "评价组", initials: "林", hue: 158 },
    han: { name: "韩澄", role: "客服数据", initials: "韩", hue: 196 },
    shen: { name: "沈见远", role: "设计采集", initials: "沈", hue: 132 },
    wang: { name: "王倩", role: "转化", initials: "王", hue: 32 },
    zhao: { name: "赵启明", role: "数据监控", initials: "赵", hue: 12 },
    su: { name: "苏晚", role: "报表", initials: "苏", hue: 262 },
    zhouqi: { name: "周琪", role: "值班", initials: "周", hue: 318 },
  },
  types: {
    review: "评价采集",
    chat: "聊天记录采集",
    draw: "绘图记录采集",
    conv: "转化率监控",
    monitor: "数据监控",
    report: "报表任务",
  },
  tasks: [
    {
      id: "TC-3118",
      title: "抖音直播间聊天记录采集",
      type: "chat",
      status: "待流转",
      owner: "han",
      action: "上一手未接，等值班确认直播排期",
      channel: "抖音直播间 · 9 个点位",
      pointsDone: 5,
      pointsTotal: 9,
      pointsNote: "5 个直播间已落库，剩余 4 个等开播后补采。",
      pointGroups: [
        { name: "华东直播间", done: 3, total: 3 },
        { name: "华南直播间", done: 2, total: 3 },
        { name: "全国大场", done: 0, total: 3 },
      ],
      lastRunAt: "2026-08-18T08:35:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 采集 412 条会话",
      nextTransferAt: "2026-08-18T09:20:00+08:00",
      nextTransferTo: "zhouqi",
    },
    {
      id: "TC-3110",
      title: "旗舰店聊天记录评价与数据采集",
      type: "chat",
      status: "运行中",
      owner: "han",
      action: "正在拉取天猫旗舰店会话",
      channel: "天猫 + 京东 · 20 个点位",
      pointsDone: 12,
      pointsTotal: 20,
      pointsNote: "华东 12 店已完成，华南与京东共 8 店待拉会话。",
      pointGroups: [
        { name: "天猫华东", done: 8, total: 8 },
        { name: "天猫华南", done: 4, total: 6 },
        { name: "京东全国", done: 0, total: 6 },
      ],
      lastRunAt: "2026-08-18T09:10:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 采集 1,284 条会话",
      nextTransferAt: "2026-08-18T10:15:00+08:00",
      nextTransferTo: "zhouqi",
    },
    {
      id: "TC-3102",
      title: "天猫旗舰店评价采集",
      type: "review",
      status: "运行中",
      owner: "lin",
      action: "回写近 24 小时新增评价",
      channel: "天猫旗舰 · 12 个点位",
      pointsDone: 8,
      pointsTotal: 12,
      pointsNote: "12 个旗舰店点位，已采 8 店，4 店排队中。",
      pointGroups: [
        { name: "服饰旗舰", done: 4, total: 5 },
        { name: "家清旗舰", done: 3, total: 4 },
        { name: "食品旗舰", done: 1, total: 3 },
      ],
      lastRunAt: "2026-08-18T08:55:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 入库 936 条评价",
      nextTransferAt: "2026-08-18T11:40:00+08:00",
      nextTransferTo: "zhao",
    },
    {
      id: "TC-3121",
      title: "店铺转化率监控",
      type: "conv",
      status: "运行中",
      owner: "wang",
      action: "核对主搜与购物车漏斗",
      channel: "全渠道漏斗 · 18 个点位",
      pointsDone: 15,
      pointsTotal: 18,
      pointsNote: "18 个监控点位出数 15 个，3 个直播间口径待补。",
      pointGroups: [
        { name: "主搜入口", done: 6, total: 6 },
        { name: "购物车", done: 6, total: 6 },
        { name: "直播间", done: 3, total: 6 },
      ],
      lastRunAt: "2026-08-18T09:20:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 全站转化率 3.6%",
      nextTransferAt: "2026-08-18T12:20:00+08:00",
      nextTransferTo: "zhouqi",
    },
    {
      id: "TC-3096",
      title: "商详绘图记录采集",
      type: "draw",
      status: "待流转",
      owner: "shen",
      action: "等设计组回传剩余 4 店主图",
      channel: "主图 / 商详 · 10 个点位",
      pointsDone: 6,
      pointsTotal: 10,
      pointsNote: "10 个绘图点位，6 店已回传，4 店在设计排期里。",
      pointGroups: [
        { name: "主图", done: 4, total: 5 },
        { name: "商详长图", done: 2, total: 5 },
      ],
      lastRunAt: "2026-08-18T07:40:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 回传 6 店设计稿",
      nextTransferAt: "2026-08-18T14:00:00+08:00",
      nextTransferTo: "lin",
    },
    {
      id: "TC-3130",
      title: "日报报表任务",
      type: "report",
      status: "待流转",
      owner: "su",
      action: "等华南口径收口后再出全国表",
      channel: "华东 / 华南 / 全国 · 3 个点位",
      pointsDone: 1,
      pointsTotal: 3,
      pointsNote: "华东日报已出，华南与全国两份等数据齐。",
      pointGroups: [
        { name: "华东日报", done: 1, total: 1 },
        { name: "华南日报", done: 0, total: 1 },
        { name: "全国日报", done: 0, total: 1 },
      ],
      lastRunAt: "2026-08-18T08:10:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 已出华东日报 1 份",
      nextTransferAt: "2026-08-18T16:00:00+08:00",
      nextTransferTo: "zhouqi",
    },
    {
      id: "TC-3088",
      title: "实时成交数据监控",
      type: "monitor",
      status: "已阻塞",
      owner: "zhao",
      action: "京东订单接口超时，等重试窗口",
      channel: "成交看板 · 16 个点位",
      pointsDone: 4,
      pointsTotal: 16,
      pointsNote: "16 个成交监控点位，仅天猫 4 店有数，京东 12 店空窗。",
      pointGroups: [
        { name: "天猫成交", done: 4, total: 4 },
        { name: "京东成交", done: 0, total: 8 },
        { name: "抖音成交", done: 0, total: 4 },
      ],
      lastRunAt: "2026-08-18T09:05:00+08:00",
      lastRunOk: false,
      lastRunText: "失败 · 京东接口超时 12 次",
      nextTransferAt: "2026-08-19T09:30:00+08:00",
      nextTransferTo: "su",
    },
    {
      id: "TC-3075",
      title: "周报报表任务",
      type: "report",
      status: "本轮已完成",
      owner: "su",
      action: "三份周报已归档",
      channel: "周报 · 3 个点位",
      pointsDone: 3,
      pointsTotal: 3,
      pointsNote: "华东、华南、全国三份周报均已归档。",
      pointGroups: [
        { name: "华东周报", done: 1, total: 1 },
        { name: "华南周报", done: 1, total: 1 },
        { name: "全国周报", done: 1, total: 1 },
      ],
      lastRunAt: "2026-08-17T18:20:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 已归档 3 份周报",
      nextTransferAt: "2026-08-17T18:20:00+08:00",
      nextTransferTo: "zhouqi",
    },
  ],
};
