/* 任务流转中心 / Mission Transfer Center — 电商采集与监控任务（示例数据） */
window.TCF_DATA = {
  boardTitle: "任务流转中心",
  boardTitleEn: "Mission Transfer Center",
  company: "华东零售",
  /* 页面以该时间点作为“现在”，保证演示数据的相对时间稳定 */
  now: "2026-08-19T09:30:00+08:00",
  viewer: { name: "周琪", team: "值班", initials: "周" },
  tasks: [
    {
      id: "FL-3017",
      title: "聊天记录采集",
      type: "chat",
      typeLabel: "聊天采集",
      status: "运行中",
      owner: { name: "韩澄", team: "客服数据", initials: "韩", hue: 190 },
      action: "正在拉取天猫旗舰店会话",
      pointsDone: 12,
      pointsTotal: 20,
      pointsNote: "20 个店铺点位：华东 12 店已完成会话拉取，华南 8 店排队中。",
      lastRunAt: "2026-08-19T08:58:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 采集 1,368 条会话",
      nextTransferAt: "2026-08-19T10:30:00+08:00",
      nextTo: "周琪",
      channel: "天猫 + 京东",
    },
    {
      id: "FL-3021",
      title: "旗舰店评价采集",
      type: "review",
      typeLabel: "评价采集",
      status: "运行中",
      owner: { name: "林晓禾", team: "评价组", initials: "林", hue: 160 },
      action: "回写近 24 小时新增评价",
      pointsDone: 9,
      pointsTotal: 14,
      pointsNote: "14 个旗舰店点位，已采 9 店；剩余 5 店等待反爬冷却窗口。",
      lastRunAt: "2026-08-19T08:40:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 入库 1,052 条评价",
      nextTransferAt: "2026-08-19T11:05:00+08:00",
      nextTo: "赵启明",
      channel: "天猫旗舰",
    },
    {
      id: "FL-3025",
      title: "店铺转化率监控",
      type: "conv",
      typeLabel: "转化率监控",
      status: "运行中",
      owner: { name: "王倩", team: "转化", initials: "王", hue: 38 },
      action: "核对主搜与购物车漏斗",
      pointsDone: 16,
      pointsTotal: 18,
      pointsNote: "18 个漏斗监控点位，剩 2 个直播间尚未出数。",
      lastRunAt: "2026-08-19T09:12:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 全站转化率 3.4%",
      nextTransferAt: "2026-08-19T12:40:00+08:00",
      nextTo: "周琪",
      channel: "全渠道漏斗",
    },
    {
      id: "FL-3008",
      title: "商详绘图记录采集",
      type: "draw",
      typeLabel: "绘图采集",
      status: "待流转",
      owner: { name: "沈见远", team: "设计采集", initials: "沈", hue: 145 },
      action: "等待设计组回传剩余 3 店",
      pointsDone: 7,
      pointsTotal: 10,
      pointsNote: "10 个商详绘图点位，7 店已回传主图与详情设计稿。",
      lastRunAt: "2026-08-19T07:35:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 回传 7 店设计稿",
      nextTransferAt: "2026-08-19T14:30:00+08:00",
      nextTo: "林晓禾",
      channel: "主图 / 商详",
    },
    {
      id: "FL-3030",
      title: "日报报表任务",
      type: "report",
      typeLabel: "报表任务",
      status: "待流转",
      owner: { name: "苏晚", team: "报表", initials: "苏", hue: 200 },
      action: "等华南场次收口后再出全国表",
      pointsDone: 1,
      pointsTotal: 3,
      pointsNote: "华东 / 华南 / 全国 3 个报表点位：华东已出，其余待流转。",
      lastRunAt: "2026-08-19T08:05:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 已出华东日报",
      nextTransferAt: "2026-08-19T16:00:00+08:00",
      nextTo: "周琪",
      channel: "华东 / 华南 / 全国",
    },
    {
      id: "FL-2996",
      title: "实时成交数据监控",
      type: "monitor",
      typeLabel: "数据监控",
      status: "已阻塞",
      owner: { name: "赵启明", team: "数据监控", initials: "赵", hue: 48 },
      action: "京东订单接口超时，等待重试窗口",
      pointsDone: 5,
      pointsTotal: 16,
      pointsNote: "16 个成交监控点位，目前仅天猫 5 店有数，京东侧全部超时。",
      lastRunAt: "2026-08-19T09:02:00+08:00",
      lastRunOk: false,
      lastRunText: "失败 · 京东订单接口超时（11 个点位无数据）",
      nextTransferAt: "2026-08-20T09:30:00+08:00",
      nextTo: "苏晚",
      channel: "成交看板",
    },
    {
      id: "FL-2988",
      title: "周报报表任务",
      type: "report",
      typeLabel: "报表任务",
      status: "本轮已完成",
      owner: { name: "苏晚", team: "报表", initials: "苏", hue: 200 },
      action: "三份周报已归档",
      pointsDone: 3,
      pointsTotal: 3,
      pointsNote: "华东、华南、全国三份周报点位均已归档，本轮关闭。",
      lastRunAt: "2026-08-18T18:20:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 归档 3 份周报",
      nextTransferAt: null,
      nextTo: null,
      channel: "周报",
    },
  ],
};
