/* Qihang Retail — internal dispatch board mock data. Board clock is fixed for demo consistency. */
window.DISPATCH = {
  company: "启航零售",
  companyEn: "Qihang Retail",
  boardTitle: "Dispatch",
  timezone: "CST",
  now: "2026-08-18T09:42:00+08:00",
  viewer: {
    id: "fang",
    name: "方芷",
    role: "PMO lead",
  },
  people: {
    fang: { name: "方芷", role: "PMO", initials: "方" },
    chen: { name: "陈予安", role: "Legal", initials: "陈" },
    lin: { name: "林晓禾", role: "Stores", initials: "林" },
    zhao: { name: "赵启明", role: "Finance", initials: "赵" },
    su: { name: "苏晚", role: "After-sales", initials: "苏" },
    zhou: { name: "周予白", role: "Brand", initials: "周" },
    han: { name: "韩澄", role: "E-comm", initials: "韩" },
    shen: { name: "沈见远", role: "Supply", initials: "沈" },
    wu: { name: "吴清", role: "East ops", initials: "吴" },
    pei: { name: "裴宁", role: "Audit", initials: "裴" },
    rong: { name: "荣知夏", role: "Seals desk", initials: "荣" },
  },
  meetings: [
    {
      id: "m-standup",
      title: "Monday ops standup",
      when: "2026-08-17T09:30:00+08:00",
      window: "week",
      room: "HQ-12F / Feishu",
    },
    {
      id: "m-seal",
      title: "Seal & legal clinic",
      when: "2026-08-17T16:00:00+08:00",
      window: "week",
      room: "Legal bay",
    },
    {
      id: "m-audit",
      title: "East store audit debrief",
      when: "2026-08-18T09:00:00+08:00",
      window: "today",
      room: "East war-room",
    },
    {
      id: "m-launch",
      title: "Autumn launch gate",
      when: "2026-08-18T11:00:00+08:00",
      window: "today",
      room: "E-comm studio",
    },
    {
      id: "m-finance",
      title: "Finance weekly close",
      when: "2026-08-18T14:30:00+08:00",
      window: "today",
      room: "F8 glass",
    },
    {
      id: "m-sla",
      title: "After-sales SLA huddle",
      when: "2026-08-18T16:00:00+08:00",
      window: "today",
      room: "CX floor",
    },
    {
      id: "m-brand",
      title: "Brand committee",
      when: "2026-08-19T10:00:00+08:00",
      window: "week",
      room: "Brand loft",
    },
    {
      id: "m-region",
      title: "Regional ops sync",
      when: "2026-08-20T15:00:00+08:00",
      window: "week",
      room: "Feishu",
    },
    {
      id: "m-recon",
      title: "Week-close reconciliation",
      when: "2026-08-21T17:00:00+08:00",
      window: "week",
      room: "Finance pit",
    },
  ],
  tasks: [
    {
      id: "OPS-2148",
      title: "Nanjing flagship mystery-shop — reopen three failed checks",
      type: "audit",
      status: "transferring",
      owner: "lin",
      action: "Collect photo evidence from store manager before noon walkthrough",
      nextTransferAt: "2026-08-18T10:15:00+08:00",
      nextTransferTo: "pei",
      meeting: "m-audit",
      region: "East · Nanjing 01",
      notes:
        "Lighting, fitting-room cleanliness, and member-desk greeting failed last Thursday. Re-audit window is today 10:15 → 裴宁.",
      trail: [
        { at: "2026-08-18T09:05:00+08:00", who: "wu", text: "Logged three fails in the East debrief." },
        { at: "2026-08-18T09:18:00+08:00", who: "lin", text: "Assigned store manager a 90-minute photo pack." },
      ],
    },
    {
      id: "OPS-2141",
      title: "July supplier settlement — company seal packet (14 chops)",
      type: "seal",
      status: "waiting",
      owner: "rong",
      action: "Hold for 陈予安 clause check on late-fee addendum",
      nextTransferAt: "2026-08-18T10:40:00+08:00",
      nextTransferTo: "chen",
      meeting: "m-seal",
      region: "HQ · Seals desk",
      notes:
        "Fourteen settlement covers plus one late-fee addendum. Desk will not stamp until legal initials the addendum page.",
      trail: [
        { at: "2026-08-17T16:20:00+08:00", who: "zhao", text: "Finance released the July packet." },
        { at: "2026-08-17T17:05:00+08:00", who: "rong", text: "Queued at seals desk; blocked on addendum." },
      ],
    },
    {
      id: "OPS-2136",
      title: "Chengdu franchise agreement — Q3 legal redline",
      type: "review",
      status: "in-review",
      owner: "chen",
      action: "Mark territory exclusivity and fit-out subsidy clauses",
      nextTransferAt: "2026-08-18T11:30:00+08:00",
      nextTransferTo: "fang",
      meeting: "m-standup",
      region: "West · Chengdu",
      notes:
        "Franchisee asked for 18-month exclusivity. Legal to return a redline before PMO routes to regional GM.",
      trail: [
        { at: "2026-08-17T10:10:00+08:00", who: "fang", text: "Opened from Monday standup, due same-week." },
        { at: "2026-08-18T08:50:00+08:00", who: "chen", text: "First pass done; exclusivity still open." },
      ],
    },
    {
      id: "OPS-2152",
      title: "Autumn e-comm SKU freeze — launch gate pack",
      type: "launch",
      status: "pending",
      owner: "han",
      action: "Lock 42 new SKUs and drop 6 late creatives from the grid",
      nextTransferAt: "2026-08-18T11:00:00+08:00",
      nextTransferTo: "zhou",
      meeting: "m-launch",
      region: "HQ · E-comm",
      notes:
        "Gate meeting is 11:00. Brand needs the freeze list 15 minutes prior so packaging reprints can be scheduled.",
      trail: [
        { at: "2026-08-18T08:30:00+08:00", who: "han", text: "Merch freeze draft circulated." },
      ],
    },
    {
      id: "OPS-2129",
      title: "WeChat Pay ↔ ERP reconciliation, week 33",
      type: "recon",
      status: "blocked",
      owner: "zhao",
      action: "Waiting on missing ￥186,420 store batch from Suzhou 07",
      nextTransferAt: "2026-08-18T14:30:00+08:00",
      nextTransferTo: "wu",
      meeting: "m-finance",
      region: "East · Suzhou 07",
      notes:
        "Week 33 is short one POS batch. Close cannot finish until East ops re-exports the terminal file.",
      trail: [
        { at: "2026-08-17T18:40:00+08:00", who: "zhao", text: "Exception list posted to Finance weekly." },
        { at: "2026-08-18T09:12:00+08:00", who: "wu", text: "Store says USB export failed; retrying after 10:00." },
      ],
    },
    {
      id: "OPS-2144",
      title: "High-value fridge replacement — 48h after-sales SLA",
      type: "aftersales",
      status: "transferring",
      owner: "su",
      action: "Confirm installer slot and door-to-door pickup in Hangzhou",
      nextTransferAt: "2026-08-18T12:20:00+08:00",
      nextTransferTo: "shen",
      meeting: "m-sla",
      region: "East · Hangzhou 03",
      notes:
        "Member complaint #CX-90411. Unit is ￥8,990. SLA clock started yesterday 16:20; transfer to supply for swap stock at 12:20.",
      trail: [
        { at: "2026-08-17T16:22:00+08:00", who: "su", text: "Opened SLA ticket; photo of compressor leak on file." },
        { at: "2026-08-18T09:00:00+08:00", who: "su", text: "Customer confirmed home access 13:00–17:00." },
      ],
    },
    {
      id: "OPS-2118",
      title: "Warehouse overtime policy — weekly action from standup",
      type: "weekly",
      status: "pending",
      owner: "shen",
      action: "Draft two-week cap and send to regional GMs for sign-off",
      nextTransferAt: "2026-08-18T15:00:00+08:00",
      nextTransferTo: "fang",
      meeting: "m-standup",
      region: "HQ · Supply",
      notes:
        "Night-shift OT exceeded 36h at the Kunshan DC. Action: written cap before Thursday regional sync.",
      trail: [
        { at: "2026-08-17T09:45:00+08:00", who: "fang", text: "Captured as weekly action #7." },
      ],
    },
    {
      id: "OPS-2107",
      title: "Packaging reprint — autumn sleeve after brand committee",
      type: "review",
      status: "waiting",
      owner: "zhou",
      action: "Await print-house quotation; hold color proof overnight",
      nextTransferAt: "2026-08-19T10:00:00+08:00",
      nextTransferTo: "han",
      meeting: "m-brand",
      region: "HQ · Brand",
      notes:
        "Committee wants matte sleeve on the hero SKU. Proof cannot ship to e-comm until Wednesday 10:00.",
      trail: [
        { at: "2026-08-15T14:00:00+08:00", who: "zhou", text: "Briefed print house; first proof due tonight." },
      ],
    },
    {
      id: "OPS-2094",
      title: "Wuxi 04 store audit — cash-drawer variance follow-up",
      type: "audit",
      status: "in-review",
      owner: "pei",
      action: "Review CCTV clip vs. shift log for 12 Aug close",
      nextTransferAt: "2026-08-18T16:45:00+08:00",
      nextTransferTo: "zhao",
      meeting: "m-audit",
      region: "East · Wuxi 04",
      notes:
        "￥2,180 short on 12 Aug. Audit holds the clip; finance receives the write-up at 16:45.",
      trail: [
        { at: "2026-08-16T11:20:00+08:00", who: "pei", text: "Pulled drawer tape and roster." },
        { at: "2026-08-18T08:10:00+08:00", who: "pei", text: "CCTV request approved by East ops." },
      ],
    },
    {
      id: "OPS-2088",
      title: "HR seal on two store-manager appointment letters",
      type: "seal",
      status: "done",
      owner: "rong",
      action: "Stamped and filed; copies with East ops",
      nextTransferAt: "2026-08-18T08:30:00+08:00",
      nextTransferTo: "wu",
      meeting: "m-seal",
      region: "East · HR",
      notes: "Both letters left the seals desk at 08:30. Closed after Wu acknowledged receipt.",
      trail: [
        { at: "2026-08-17T16:40:00+08:00", who: "rong", text: "Verified ID pages." },
        { at: "2026-08-18T08:30:00+08:00", who: "wu", text: "Received scanned copies." },
      ],
    },
    {
      id: "OPS-2155",
      title: "Member-day landing page — legal claims review",
      type: "review",
      status: "pending",
      owner: "han",
      action: "Send claim list (price, gift, lottery) to legal by 13:00",
      nextTransferAt: "2026-08-18T13:00:00+08:00",
      nextTransferTo: "chen",
      meeting: "m-launch",
      region: "HQ · E-comm",
      notes:
        "Sept 3 member day. Three promotional claims still unapproved. Legal needs the list before afternoon clinic overflow.",
      trail: [
        { at: "2026-08-18T09:25:00+08:00", who: "han", text: "Drafted claim table from design lock." },
      ],
    },
    {
      id: "OPS-2076",
      title: "Alipay vs. bank statement — weekend festival stall",
      type: "recon",
      status: "done",
      owner: "zhao",
      action: "Variance explained; booked to festival clearing account",
      nextTransferAt: "2026-08-17T18:00:00+08:00",
      nextTransferTo: "fang",
      meeting: "m-recon",
      region: "HQ · Finance",
      notes: "￥9,640 timing difference. Closed in last night's pre-close.",
      trail: [
        { at: "2026-08-17T17:10:00+08:00", who: "zhao", text: "Matched 14 stall batches." },
        { at: "2026-08-17T18:00:00+08:00", who: "fang", text: "Signed the weekly action as done." },
      ],
    },
    {
      id: "OPS-2160",
      title: "Kunming pop-up launch schedule — fixture truck slot",
      type: "launch",
      status: "blocked",
      owner: "wu",
      action: "Carrier missed Monday dock; rebook before Thursday sync",
      nextTransferAt: "2026-08-20T15:00:00+08:00",
      nextTransferTo: "shen",
      meeting: "m-region",
      region: "West · Kunming",
      notes:
        "Pop-up opens 28 Aug. Fixture truck no-show on 17 Aug. Supply must confirm a replacement slot in the Thursday regional sync.",
      trail: [
        { at: "2026-08-17T20:15:00+08:00", who: "wu", text: "Flagged no-show to supply on-call." },
      ],
    },
    {
      id: "OPS-2149",
      title: "Return-to-vendor batch — after-sales weeklies",
      type: "aftersales",
      status: "in-review",
      owner: "su",
      action: "Approve 11 small-appliance RMA lines over ￥500",
      nextTransferAt: "2026-08-18T16:00:00+08:00",
      nextTransferTo: "zhao",
      meeting: "m-sla",
      region: "HQ · CX",
      notes: "Weekly RMA stack. Finance wants coded reason codes before the 16:00 huddle ends.",
      trail: [
        { at: "2026-08-18T09:02:00+08:00", who: "su", text: "Pulled 11 lines from the CX queue." },
      ],
    },
    {
      id: "OPS-2061",
      title: "West region weekly actions — close last week's six items",
      type: "weekly",
      status: "done",
      owner: "fang",
      action: "All six signed; archive attached to Monday notes",
      nextTransferAt: "2026-08-17T11:00:00+08:00",
      nextTransferTo: "wu",
      meeting: "m-standup",
      region: "West",
      notes: "Closed in Monday standup. Kept on the board for the weekly done count.",
      trail: [
        { at: "2026-08-17T11:00:00+08:00", who: "fang", text: "Archived actions 1–6." },
      ],
    },
    {
      id: "OPS-2164",
      title: "Store-audit sampling plan — 22 Aug weekend wave",
      type: "audit",
      status: "pending",
      owner: "pei",
      action: "Lock 12-store sample and notify area managers",
      nextTransferAt: "2026-08-19T17:30:00+08:00",
      nextTransferTo: "lin",
      meeting: "m-audit",
      region: "National",
      notes:
        "Weekend wave covers 12 stores across East and West. Sample must be frozen 48h prior so managers cannot restage.",
      trail: [
        { at: "2026-08-18T09:08:00+08:00", who: "pei", text: "Random seed drawn; waiting PMO confirm." },
      ],
    },
    {
      id: "OPS-2133",
      title: "Board resolution extract — seal for bank mandate update",
      type: "seal",
      status: "transferring",
      owner: "rong",
      action: "Walk packet to legal, then bank courier at 15:10",
      nextTransferAt: "2026-08-18T15:10:00+08:00",
      nextTransferTo: "zhao",
      meeting: "m-finance",
      region: "HQ · Seals desk",
      notes:
        "New signatories for the operating account. Courier leaves at 15:10; finance must be at the dock.",
      trail: [
        { at: "2026-08-18T09:33:00+08:00", who: "rong", text: "Extract printed; waiting legal wet-ink." },
      ],
    },
    {
      id: "OPS-2054",
      title: "Q2 after-sales quality review — closed with CX notes",
      type: "aftersales",
      status: "done",
      owner: "su",
      action: "Filed; no residual transfers",
      nextTransferAt: "2026-08-16T17:00:00+08:00",
      nextTransferTo: "fang",
      meeting: "m-sla",
      region: "HQ · CX",
      notes: "Quarterly review closed Saturday. Shown in this week's done set.",
      trail: [
        { at: "2026-08-16T17:00:00+08:00", who: "su", text: "Uploaded the Q2 pack." },
      ],
    },
  ],
};
