/* 任务流转中心 / Mission Transfer Center — 电商运营采集与监控任务 */
window.TRANSFER_CENTER = {
  company: "华东零售",
  boardTitle: "任务流转中心",
  boardTitleEn: "Mission Transfer Center",
  timezone: "CST",
  now: "2026-08-18T09:42:00+08:00",
  viewer: { id: "zhouqi", name: "周琪", role: "值班", initials: "周" },
  people: {
    lin: { name: "林晓禾", role: "评价组", initials: "林" },
    han: { name: "韩澄", role: "客服数据", initials: "韩" },
    shen: { name: "沈见远", role: "设计采集", initials: "沈" },
    wang: { name: "王倩", role: "转化", initials: "王" },
    zhao: { name: "赵启明", role: "数据监控", initials: "赵" },
    su: { name: "苏晚", role: "报表", initials: "苏" },
    zhouqi: { name: "周琪", role: "值班", initials: "周" },
  },
  tasks: [
    {
      id: "TF-2108",
      title: "聊天记录评价与数据采集",
      type: "chat",
      status: "运行中",
      owner: "han",
      action: "正在拉取天猫旗舰店会话",
      pointsDone: 12,
      pointsTotal: 20,
      pointsNote: "已完成华东 12 店，剩余华南 8 店待拉会话。",
      lastRunAt: "2026-08-18T09:10:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 采集 1,284 条会话",
      nextLabel: "今天 10:15",
      nextTransferAt: "2026-08-18T10:15:00+08:00",
      nextTransferTo: "zhouqi",
      channel: "天猫 + 京东 · 20 个点位",
    },
    {
      id: "TF-2104",
      title: "旗舰店评价采集",
      type: "review",
      status: "运行中",
      owner: "lin",
      action: "回写近 24 小时新增评价",
      pointsDone: 8,
      pointsTotal: 12,
      pointsNote: "12 个旗舰店点位，已采 8 店。",
      lastRunAt: "2026-08-18T08:55:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 入库 936 条评价",
      nextLabel: "今天 11:40",
      nextTransferAt: "2026-08-18T11:40:00+08:00",
      nextTransferTo: "zhao",
      channel: "天猫旗舰 · 12 个点位",
    },
    {
      id: "TF-2112",
      title: "店铺转化率监控",
      type: "conv",
      status: "运行中",
      owner: "wang",
      action: "核对主搜与购物车漏斗",
      pointsDone: 15,
      pointsTotal: 18,
      pointsNote: "18 个监控点位，剩 3 个直播间未出数。",
      lastRunAt: "2026-08-18T09:20:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 全站转化率 3.6%",
      nextLabel: "今天 12:20",
      nextTransferAt: "2026-08-18T12:20:00+08:00",
      nextTransferTo: "zhouqi",
      channel: "全渠道漏斗 · 18 个点位",
    },
    {
      id: "TF-2099",
      title: "商详绘图记录采集",
      type: "draw",
      status: "待流转",
      owner: "shen",
      action: "等待设计组回传剩余 4 店",
      pointsDone: 6,
      pointsTotal: 10,
      pointsNote: "10 个商详绘图点位，6 店已回传。",
      lastRunAt: "2026-08-18T07:40:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 回传 6 店设计稿",
      nextLabel: "今天 14:00",
      nextTransferAt: "2026-08-18T14:00:00+08:00",
      nextTransferTo: "lin",
      channel: "主图/商详 · 10 个点位",
    },
    {
      id: "TF-2116",
      title: "日报报表任务",
      type: "report",
      status: "待流转",
      owner: "su",
      action: "等华南场次收口后再出全国表",
      pointsDone: 1,
      pointsTotal: 3,
      pointsNote: "华东已出，华南与全国待流转。",
      lastRunAt: "2026-08-18T08:10:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 已出华东日报",
      nextLabel: "今天 16:00",
      nextTransferAt: "2026-08-18T16:00:00+08:00",
      nextTransferTo: "zhouqi",
      channel: "华东 / 华南 / 全国 · 3 个点位",
    },
    {
      id: "TF-2088",
      title: "实时成交数据监控",
      type: "monitor",
      status: "已阻塞",
      owner: "zhao",
      action: "京东订单接口超时，等待重试窗口",
      pointsDone: 4,
      pointsTotal: 16,
      pointsNote: "16 个成交监控点位，仅天猫 4 店有数。",
      lastRunAt: "2026-08-18T09:05:00+08:00",
      lastRunOk: false,
      lastRunText: "失败 · 京东接口超时",
      nextLabel: "明天 09:30",
      nextTransferAt: "2026-08-19T09:30:00+08:00",
      nextTransferTo: "su",
      channel: "成交看板 · 16 个点位",
    },
    {
      id: "TF-2071",
      title: "周报报表任务",
      type: "report",
      status: "本轮已完成",
      owner: "su",
      action: "三份周报已归档",
      pointsDone: 3,
      pointsTotal: 3,
      pointsNote: "华东、华南、全国三份均已归档。",
      lastRunAt: "2026-08-17T18:20:00+08:00",
      lastRunOk: true,
      lastRunText: "成功 · 已归档 3 份周报",
      nextLabel: "已结束",
      nextTransferAt: "2026-08-17T18:20:00+08:00",
      nextTransferTo: "zhouqi",
      channel: "周报 · 3 个点位",
    },
  ],
};
