/* 与其他变体同一批公司内部任务：审阅、用印、巡检、上市、售后、周行动、对账 */
window.OPS_DESKTOP = {
  company: "华东零售",
  boardTitle: "运营桌面",
  timezone: "CST",
  now: "2026-08-18T09:42:00+08:00",
  viewer: { id: "zhouqi", name: "周琪", role: "运营办", initials: "周" },
  followStatuses: ["流转中", "待跟进", "已阻塞", "等待中"],
  people: {
    limin: { name: "李敏", role: "大客户", initials: "李" },
    zhangkai: { name: "张凯", role: "法务", initials: "张" },
    dianzhang: { name: "陈店长", role: "门店", initials: "陈" },
    wangqian: { name: "王倩", role: "运营", initials: "王" },
    zhijian: { name: "质检", role: "质量", initials: "质" },
    zhouqi: { name: "周琪", role: "运营办", initials: "周" },
    caiwu: { name: "财务", role: "财务", initials: "财" },
  },
  meetings: [
    { id: "m-review", title: "华东大客户季度复盘会", when: "2026-08-18T09:00:00+08:00", window: "today", room: "总部 12F" },
    { id: "m-launch", title: "渠道上市对齐会", when: "2026-08-18T11:00:00+08:00", window: "today", room: "电商工作室" },
    { id: "m-seal", title: "供应商合同评审", when: "2026-08-17T16:00:00+08:00", window: "week", room: "法务隔间" },
    { id: "m-audit", title: "门店巡检复盘", when: "2026-08-17T15:00:00+08:00", window: "week", room: "华东作战室" },
    { id: "m-weekly", title: "周例会", when: "2026-08-17T09:30:00+08:00", window: "week", room: "飞书" },
  ],
  tasks: [
    {
      id: "OPS-4827",
      title: "华东大客户季度复盘",
      type: "review",
      status: "进行中",
      owner: "limin",
      action: "整理会议纪要待确认",
      result: "客户已确认本季续约意向",
      nextLabel: "今天 10:30",
      nextTransferAt: "2026-08-18T10:30:00+08:00",
      nextTransferTo: "zhouqi",
      meeting: "m-review",
      meetingFlag: "today",
      region: "华东 · 大客户部",
    },
    {
      id: "OPS-4821",
      title: "供应商合同用印",
      type: "seal",
      status: "流转中",
      owner: "zhangkai",
      action: "法务审批中",
      result: "商务条款已核过，待用法务审",
      nextLabel: "今天 14:00",
      nextTransferAt: "2026-08-18T14:00:00+08:00",
      nextTransferTo: "caiwu",
      meeting: "m-seal",
      meetingFlag: "week",
      region: "总部 · 用印台",
    },
    {
      id: "OPS-4816",
      title: "南京新街口店巡检整改",
      type: "audit",
      status: "待跟进",
      owner: "dianzhang",
      action: "回传整改照片",
      result: "陈列与消防各有 2 项待改",
      nextLabel: "明天 09:00",
      nextTransferAt: "2026-08-19T09:00:00+08:00",
      nextTransferTo: "zhouqi",
      meeting: "m-audit",
      meetingFlag: "week",
      region: "华东 · 南京新街口",
    },
    {
      id: "OPS-4830",
      title: "新品上市排期对齐",
      type: "launch",
      status: "进行中",
      owner: "wangqian",
      action: "约齐渠道会",
      result: "电商档期已锁 9 月 8 日",
      nextLabel: "今天 16:30",
      nextTransferAt: "2026-08-18T16:30:00+08:00",
      nextTransferTo: "limin",
      meeting: "m-launch",
      meetingFlag: "today",
      region: "总部 · 电商",
    },
    {
      id: "OPS-4809",
      title: "售后升级单 #4821",
      type: "aftersales",
      status: "已阻塞",
      owner: "zhijian",
      action: "等责任判定",
      result: "客服已升级至质量部",
      nextLabel: "明天 11:00",
      nextTransferAt: "2026-08-19T11:00:00+08:00",
      nextTransferTo: "caiwu",
      meeting: null,
      meetingFlag: null,
      region: "总部 · 售后",
    },
    {
      id: "OPS-4798",
      title: "周例会行动项回收",
      type: "weekly",
      status: "已完成",
      owner: "zhouqi",
      action: "已关闭 7 项行动项",
      result: "",
      nextLabel: "已结束",
      nextTransferAt: "2026-08-17T11:00:00+08:00",
      nextTransferTo: "zhouqi",
      meeting: "m-weekly",
      meetingFlag: "week",
      region: "总部 · 运营办",
    },
    {
      id: "OPS-4833",
      title: "渠道费用对账 8 月",
      type: "recon",
      status: "等待中",
      owner: "caiwu",
      action: "待回传差异表",
      result: "已对上 6 家，差 2 家未回",
      nextLabel: "周四 15:00",
      nextTransferAt: "2026-08-20T15:00:00+08:00",
      nextTransferTo: "zhouqi",
      meeting: null,
      meetingFlag: null,
      region: "总部 · 财务",
    },
  ],
};
